# Site settings
title: Blasé Malaise | Stef Gab's Blog
short_title: Blasé Malaise
email: steve.guo@carleton.ca
description: > # this means to ignore newlines until "baseurl:"
  Stef Gab's Blog — Code/Game/Life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scguo.github.io" # the base hostname & protocol for your site
github_username: scguo
linkedin_username: scguo
googleplus_username: <redacted />
steam_username: newThrow

# Build settings
markdown: kramdown
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
exclude: ["Gemfile",
  "Gemfile.lock",
  "bower.json",
  "/bower_components/bootstrap-sass/*.md",
  "/bower_components/font-awesome-sass/*.md",
  "readme.md"
]

# Outputting
permalink: pretty

# Swag
plugins:
  - jekyll-sitemap
  
