# Site settings
title: Blasé Malaise
email: steve.guo@carleton.ca
description: > # this means to ignore newlines until "baseurl:"
  Steve Guo's blog — Code/Game/Life
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://scguo.github.io" # the base hostname & protocol for your site
github_username:  scguo
linkedin_username: scguo
googleplus_username: SteveGuo1
steam_username: newThrow

# Build settings
markdown: kramdown

# Outputting
permalink: pretty

# Swag
# sass:
  # loading path from site root, default to _sass
  # sass_dir: bower_components/bootstrap-sass/assets/stylesheets
  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9kB, compressed 122,4kB
  # style: compressed